"""Maintain Model 02's rolling four-month joint Gaussian score posterior.

The filter state is the eight-vector

``z = (growth[m-3], inflation[m-3], ..., growth[m], inflation[m])``.

It contains uncertainty about the continuous economic scores generated by the
VAR dynamics and release observations.  The separate score-to-quadrant mapping
covariance is deliberately *not* part of this state.  Mapping covariance is
added only when a monthly marginal, or the complete four-month path, is mapped
to quadrant probabilities.  Keeping those two uncertainties separate prevents
the mapping covariance from being counted once in transition propagation and a
second time at reporting.

The module provides pure, immutable numerical primitives for:

* building an initial four-month path from an oldest Gaussian or exact score;
* rolling the path forward through a block VAR transformation that adds process
  covariance ``Q`` only to the newly appended month;
* applying partial linear-Gaussian release observations with the numerically
  stable Joseph covariance update;
* conditioning a selected month on an exact two-score observation; and
* reporting soft quadrant probabilities after adding mapping uncertainty.

An exact score observation removes all posterior variance and cross-covariance
for that month's latent score.  It remains a *soft* quadrant observation at
readout because revision and component-disagreement uncertainty are represented
by the mapping covariance.  Later release evidence about an already exact month
is diagnostically evaluated but cannot change the state.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
import math

import numpy as np
import pandas as pd
from scipy.stats import norm, qmc

from regime_allocation.models.m02_soft_composite.probability_map import (
    REGIME_ORDER,
    gaussian_quadrant_weights,
)


STATE_MONTHS = 4
AXES_PER_MONTH = 2
STATE_DIMENSION = STATE_MONTHS * AXES_PER_MONTH


def _validated_month(value: object, *, name: str) -> pd.Timestamp:
    """Return a timezone-naive month-start timestamp."""

    month = pd.Timestamp(value)
    if month.tzinfo is not None:
        raise ValueError(f"{name} must be timezone-naive")
    if month.day != 1 or month != month.normalize():
        raise ValueError(f"{name} must be normalized to month start")
    return month


def _validated_vector(value: object, size: int, *, name: str) -> np.ndarray:
    """Return a finite defensive copy of a one-dimensional vector."""

    vector = np.asarray(value, dtype=float)
    if vector.shape != (size,) or not np.isfinite(vector).all():
        raise ValueError(f"{name} must be a finite vector of length {size}")
    return vector.copy()


def _validated_matrix(
    value: object,
    shape: tuple[int, int],
    *,
    name: str,
) -> np.ndarray:
    """Return a finite defensive copy of a matrix with the requested shape."""

    matrix = np.asarray(value, dtype=float)
    if matrix.shape != shape or not np.isfinite(matrix).all():
        raise ValueError(f"{name} must be a finite {shape[0]}x{shape[1]} matrix")
    return matrix.copy()


def _validated_covariance(
    value: object,
    dimension: int,
    *,
    name: str,
    positive_definite: bool = False,
) -> np.ndarray:
    """Validate a covariance and remove only roundoff-scale negative modes."""

    covariance = _validated_matrix(value, (dimension, dimension), name=name)
    if not np.allclose(covariance, covariance.T, atol=1.0e-11, rtol=1.0e-11):
        raise ValueError(f"{name} must be symmetric")
    covariance = (covariance + covariance.T) / 2.0
    eigenvalues, eigenvectors = np.linalg.eigh(covariance)
    scale = max(1.0, float(np.max(np.abs(eigenvalues))))
    tolerance = 1.0e-10 * scale
    if float(eigenvalues[0]) < -tolerance:
        raise ValueError(f"{name} must be positive semidefinite")
    if positive_definite and float(eigenvalues[0]) <= tolerance:
        raise ValueError(f"{name} must be positive definite")
    if float(eigenvalues[0]) < 0.0:
        covariance = (eigenvectors * np.maximum(eigenvalues, 0.0)) @ eigenvectors.T
        covariance = (covariance + covariance.T) / 2.0
    return covariance


def _month_slice(position: int) -> slice:
    """Return the state-vector slice for a zero-based month position."""

    if position < 0 or position >= STATE_MONTHS:
        raise IndexError("month position is outside the four-month state")
    start = AXES_PER_MONTH * position
    return slice(start, start + AXES_PER_MONTH)


@dataclass(frozen=True)
class VarDynamics:
    """One two-dimensional VAR edge used to append a monthly score.

    ``next_score = intercept + transition @ current_score + innovation``
    with ``innovation ~ N(0, innovation_covariance)``.
    """

    intercept: np.ndarray
    transition: np.ndarray
    innovation_covariance: np.ndarray

    def __post_init__(self) -> None:
        intercept = _validated_vector(self.intercept, 2, name="VAR intercept")
        transition = _validated_matrix(
            self.transition, (2, 2), name="VAR transition"
        )
        innovation = _validated_covariance(
            self.innovation_covariance,
            2,
            name="VAR innovation covariance",
        )
        intercept.setflags(write=False)
        transition.setflags(write=False)
        innovation.setflags(write=False)
        object.__setattr__(self, "intercept", intercept)
        object.__setattr__(self, "transition", transition)
        object.__setattr__(self, "innovation_covariance", innovation)


def _default_exact_values() -> np.ndarray:
    return np.full((STATE_MONTHS, AXES_PER_MONTH), np.nan, dtype=float)


@dataclass(frozen=True)
class JointGaussianState:
    """Immutable Gaussian posterior for four consecutive monthly score pairs."""

    reference_months: tuple[pd.Timestamp, ...]
    mean: np.ndarray
    covariance: np.ndarray
    exact_mask: tuple[bool, ...] = (False,) * STATE_MONTHS
    exact_values: np.ndarray = field(default_factory=_default_exact_values)

    def __post_init__(self) -> None:
        if len(self.reference_months) != STATE_MONTHS:
            raise ValueError("joint state must contain exactly four reference months")
        months = tuple(
            _validated_month(value, name="reference month")
            for value in self.reference_months
        )
        for previous, current in zip(months, months[1:]):
            expected = (previous.to_period("M") + 1).to_timestamp()
            if current != expected:
                raise ValueError("joint-state reference months must be consecutive")

        mean = _validated_vector(self.mean, STATE_DIMENSION, name="joint mean")
        covariance = _validated_covariance(
            self.covariance,
            STATE_DIMENSION,
            name="joint covariance",
        )
        if len(self.exact_mask) != STATE_MONTHS:
            raise ValueError("exact mask must contain one flag per month")
        exact_mask = tuple(bool(value) for value in self.exact_mask)
        exact_values = np.asarray(self.exact_values, dtype=float)
        if exact_values.shape != (STATE_MONTHS, AXES_PER_MONTH):
            raise ValueError("exact values must have shape 4x2")
        exact_values = exact_values.copy()

        scale = max(1.0, float(np.max(np.abs(covariance))))
        tolerance = 1.0e-9 * scale
        for position, is_exact in enumerate(exact_mask):
            block = _month_slice(position)
            if is_exact:
                value = exact_values[position]
                if not np.isfinite(value).all():
                    raise ValueError("an exact month requires a finite score pair")
                if not np.allclose(mean[block], value, atol=1.0e-10, rtol=1.0e-10):
                    raise ValueError("exact score and posterior mean disagree")
                if (
                    np.max(np.abs(covariance[block, :])) > tolerance
                    or np.max(np.abs(covariance[:, block])) > tolerance
                ):
                    raise ValueError(
                        "an exact month's covariance and cross-covariance must be zero"
                    )
                covariance[block, :] = 0.0
                covariance[:, block] = 0.0
            elif not np.isnan(exact_values[position]).all():
                raise ValueError("a non-exact month cannot carry an exact score")

        mean.setflags(write=False)
        covariance.setflags(write=False)
        exact_values.setflags(write=False)
        object.__setattr__(self, "reference_months", months)
        object.__setattr__(self, "mean", mean)
        object.__setattr__(self, "covariance", covariance)
        object.__setattr__(self, "exact_mask", exact_mask)
        object.__setattr__(self, "exact_values", exact_values)

    def position(self, reference_month: object) -> int:
        """Return the position of a month, rejecting past or future targets."""

        month = _validated_month(reference_month, name="target reference month")
        try:
            return self.reference_months.index(month)
        except ValueError:
            if month > self.reference_months[-1]:
                raise ValueError("future target month is outside the joint state") from None
            if month < self.reference_months[0]:
                raise ValueError("expired target month is outside the joint state") from None
            raise ValueError("target reference month is outside the joint state") from None

    def marginal(self, reference_month: object) -> tuple[np.ndarray, np.ndarray]:
        """Return defensive copies of one monthly score marginal."""

        block = _month_slice(self.position(reference_month))
        return self.mean[block].copy(), self.covariance[block, block].copy()


@dataclass(frozen=True)
class LinearGaussianUpdate:
    """Posterior plus diagnostics for one release-evidence update."""

    state: JointGaussianState
    applied: bool
    reason: str
    innovation: np.ndarray
    innovation_covariance: np.ndarray
    kalman_gain: np.ndarray
    log_predictive_density: float


def _build_initial_path(
    *,
    oldest_reference_month: object,
    oldest_mean: object,
    oldest_covariance: object,
    dynamics: Sequence[VarDynamics],
    oldest_exact_score: object | None,
) -> JointGaussianState:
    """Build four joint moments by applying three sequential VAR edges."""

    if len(dynamics) != STATE_MONTHS - 1:
        raise ValueError("initialization requires exactly three VAR edges")
    oldest_month = _validated_month(
        oldest_reference_month, name="oldest reference month"
    )
    mean0 = _validated_vector(oldest_mean, 2, name="oldest mean")
    covariance0 = _validated_covariance(
        oldest_covariance, 2, name="oldest covariance"
    )
    exact_mask = [False] * STATE_MONTHS
    exact_values = _default_exact_values()
    if oldest_exact_score is not None:
        exact = _validated_vector(oldest_exact_score, 2, name="oldest exact score")
        if not np.allclose(exact, mean0, atol=1.0e-12, rtol=1.0e-12):
            raise ValueError("oldest exact score and oldest mean disagree")
        if not np.allclose(covariance0, 0.0, atol=1.0e-12, rtol=0.0):
            raise ValueError("oldest exact score requires zero oldest covariance")
        exact_mask[0] = True
        exact_values[0] = exact

    means = [mean0]
    covariance = covariance0
    for edge in dynamics:
        current_dimension = covariance.shape[0]
        last = slice(current_dimension - 2, current_dimension)
        next_mean = edge.intercept + edge.transition @ means[-1]
        cross_new_old = edge.transition @ covariance[last, :]
        next_covariance = (
            edge.transition @ covariance[last, last] @ edge.transition.T
            + edge.innovation_covariance
        )
        expanded = np.zeros((current_dimension + 2, current_dimension + 2))
        expanded[:current_dimension, :current_dimension] = covariance
        expanded[current_dimension:, :current_dimension] = cross_new_old
        expanded[:current_dimension, current_dimension:] = cross_new_old.T
        expanded[current_dimension:, current_dimension:] = next_covariance
        covariance = (expanded + expanded.T) / 2.0
        means.append(next_mean)

    months = tuple(
        (oldest_month.to_period("M") + offset).to_timestamp()
        for offset in range(STATE_MONTHS)
    )
    return JointGaussianState(
        reference_months=months,
        mean=np.concatenate(means),
        covariance=covariance,
        exact_mask=tuple(exact_mask),
        exact_values=exact_values,
    )


def initialize_joint_gaussian(
    oldest_reference_month: object,
    oldest_mean: object,
    oldest_covariance: object,
    dynamics: Sequence[VarDynamics],
) -> JointGaussianState:
    """Initialize four months from an uncertain oldest monthly score."""

    return _build_initial_path(
        oldest_reference_month=oldest_reference_month,
        oldest_mean=oldest_mean,
        oldest_covariance=oldest_covariance,
        dynamics=dynamics,
        oldest_exact_score=None,
    )


def initialize_joint_exact(
    oldest_reference_month: object,
    oldest_score: object,
    dynamics: Sequence[VarDynamics],
) -> JointGaussianState:
    """Initialize four months from an exactly observed oldest score."""

    exact = _validated_vector(oldest_score, 2, name="oldest exact score")
    return _build_initial_path(
        oldest_reference_month=oldest_reference_month,
        oldest_mean=exact,
        oldest_covariance=np.zeros((2, 2)),
        dynamics=dynamics,
        oldest_exact_score=exact,
    )


def roll_joint_gaussian(
    state: JointGaussianState,
    dynamics: VarDynamics,
    *,
    next_reference_month: object | None = None,
) -> JointGaussianState:
    """Drop the oldest month and append one month using only VAR process noise.

    The six overlapping coordinates are copied exactly by a block shift.  The
    new month is generated from the previous newest month, and ``Q`` is added
    only to its 2x2 marginal block.
    """

    expected = (state.reference_months[-1].to_period("M") + 1).to_timestamp()
    target = (
        expected
        if next_reference_month is None
        else _validated_month(next_reference_month, name="next reference month")
    )
    if target != expected:
        raise ValueError("next reference month must immediately follow the state")

    transform = np.zeros((STATE_DIMENSION, STATE_DIMENSION))
    transform[:6, 2:] = np.eye(6)
    transform[6:, 6:] = dynamics.transition
    offset = np.zeros(STATE_DIMENSION)
    offset[6:] = dynamics.intercept
    process = np.zeros((STATE_DIMENSION, STATE_DIMENSION))
    process[6:, 6:] = dynamics.innovation_covariance

    mean = offset + transform @ state.mean
    covariance = transform @ state.covariance @ transform.T + process
    exact_values = _default_exact_values()
    exact_values[:3] = state.exact_values[1:]
    return JointGaussianState(
        reference_months=(*state.reference_months[1:], target),
        mean=mean,
        covariance=covariance,
        exact_mask=(*state.exact_mask[1:], False),
        exact_values=exact_values,
    )


def _observation_inputs(
    observation: object,
    loading: object,
    noise_covariance: object,
    intercept: object | None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Normalize dimensions for a release block's observation equation."""

    design = np.asarray(loading, dtype=float)
    if design.ndim == 1:
        design = design.reshape(1, -1)
    if design.ndim != 2 or design.shape[1] != 2 or design.shape[0] < 1:
        raise ValueError("release loading must have shape kx2")
    if not np.isfinite(design).all():
        raise ValueError("release loading must be finite")
    rows = design.shape[0]
    observed = np.asarray(observation, dtype=float).reshape(-1)
    if observed.shape != (rows,) or not np.isfinite(observed).all():
        raise ValueError("release observation must contain one finite value per row")
    offset = (
        np.zeros(rows)
        if intercept is None
        else np.asarray(intercept, dtype=float).reshape(-1)
    )
    if offset.shape != (rows,) or not np.isfinite(offset).all():
        raise ValueError("release intercept must contain one finite value per row")
    raw_noise = np.asarray(noise_covariance, dtype=float)
    if raw_noise.ndim == 0 and rows == 1:
        raw_noise = raw_noise.reshape(1, 1)
    noise = _validated_covariance(
        raw_noise,
        rows,
        name="release noise covariance",
        positive_definite=True,
    )
    return observed, design, noise, offset


def update_joint_gaussian(
    state: JointGaussianState,
    reference_month: object,
    observation: object,
    loading: object,
    noise_covariance: object,
    *,
    intercept: object | None = None,
) -> LinearGaussianUpdate:
    """Apply one partial linear-Gaussian release block to a selected month.

    The observation equation is ``y = intercept + loading @ score + error``.
    Rows such as ``[1, 0]`` naturally express growth-only evidence.  Conditional
    independence between separately submitted blocks is an external modeling
    assumption; correlated indicators should instead be supplied jointly with
    their full noise covariance.
    """

    position = state.position(reference_month)
    observed, design, noise, offset = _observation_inputs(
        observation, loading, noise_covariance, intercept
    )
    block = _month_slice(position)
    global_design = np.zeros((len(observed), STATE_DIMENSION))
    global_design[:, block] = design
    innovation = observed - offset - global_design @ state.mean
    innovation_covariance = (
        global_design @ state.covariance @ global_design.T + noise
    )
    innovation_covariance = _validated_covariance(
        innovation_covariance,
        len(observed),
        name="predictive innovation covariance",
        positive_definite=True,
    )
    sign, log_determinant = np.linalg.slogdet(innovation_covariance)
    if sign <= 0.0:
        raise ValueError("predictive innovation covariance is not positive definite")
    solved_innovation = np.linalg.solve(innovation_covariance, innovation)
    log_density = float(
        -0.5
        * (
            len(observed) * math.log(2.0 * math.pi)
            + log_determinant
            + innovation @ solved_innovation
        )
    )

    if state.exact_mask[position]:
        return LinearGaussianUpdate(
            state=state,
            applied=False,
            reason="target_score_exact",
            innovation=innovation,
            innovation_covariance=innovation_covariance,
            kalman_gain=np.zeros((STATE_DIMENSION, len(observed))),
            log_predictive_density=log_density,
        )

    gain = np.linalg.solve(
        innovation_covariance,
        global_design @ state.covariance,
    ).T
    posterior_mean = state.mean + gain @ innovation
    identity_minus_kh = np.eye(STATE_DIMENSION) - gain @ global_design
    posterior_covariance = (
        identity_minus_kh @ state.covariance @ identity_minus_kh.T
        + gain @ noise @ gain.T
    )
    posterior_covariance = (posterior_covariance + posterior_covariance.T) / 2.0
    posterior = JointGaussianState(
        reference_months=state.reference_months,
        mean=posterior_mean,
        covariance=posterior_covariance,
        exact_mask=state.exact_mask,
        exact_values=state.exact_values,
    )
    return LinearGaussianUpdate(
        state=posterior,
        applied=True,
        reason="updated",
        innovation=innovation,
        innovation_covariance=innovation_covariance,
        kalman_gain=gain,
        log_predictive_density=log_density,
    )


def condition_on_exact_score(
    state: JointGaussianState,
    reference_month: object,
    score: object,
    *,
    tolerance: float = 1.0e-10,
) -> JointGaussianState:
    """Condition the joint Gaussian on an exact two-dimensional monthly score.

    Repeating an identical exact observation is idempotent.  Repeating it with
    a conflicting value is rejected rather than silently overwriting history.
    """

    if tolerance < 0.0 or not math.isfinite(tolerance):
        raise ValueError("exact-observation tolerance must be finite and nonnegative")
    position = state.position(reference_month)
    exact = _validated_vector(score, 2, name="exact score")
    if state.exact_mask[position]:
        previous = state.exact_values[position]
        if np.allclose(previous, exact, atol=tolerance, rtol=0.0):
            return state
        raise ValueError("conflicting exact score for an already exact month")

    block = _month_slice(position)
    marginal_covariance = _validated_covariance(
        state.covariance[block, block],
        2,
        name="conditioned score covariance",
        positive_definite=True,
    )
    cross_covariance = state.covariance[:, block]
    gain = np.linalg.solve(marginal_covariance, cross_covariance.T).T
    posterior_mean = state.mean + gain @ (exact - state.mean[block])
    posterior_covariance = (
        state.covariance - gain @ state.covariance[block, :]
    )
    posterior_covariance = (posterior_covariance + posterior_covariance.T) / 2.0
    posterior_mean[block] = exact
    posterior_covariance[block, :] = 0.0
    posterior_covariance[:, block] = 0.0
    exact_mask = list(state.exact_mask)
    exact_mask[position] = True
    exact_values = state.exact_values.copy()
    exact_values[position] = exact
    return JointGaussianState(
        reference_months=state.reference_months,
        mean=posterior_mean,
        covariance=posterior_covariance,
        exact_mask=tuple(exact_mask),
        exact_values=exact_values,
    )


def monthly_quadrant_probabilities(
    state: JointGaussianState,
    reference_month: object,
    mapping_covariance: object,
) -> dict[str, float]:
    """Map one monthly marginal to quadrants after adding mapping covariance."""

    mean, covariance = state.marginal(reference_month)
    omega_map = _validated_covariance(
        mapping_covariance, 2, name="mapping covariance"
    )
    _, probabilities = gaussian_quadrant_weights(mean, covariance + omega_map)
    return probabilities


def _mapping_block_covariance(
    state: JointGaussianState,
    mapping_covariances: object,
) -> np.ndarray:
    """Return a block-diagonal 8x8 covariance for path readout."""

    if isinstance(mapping_covariances, Mapping):
        raw = []
        for month in state.reference_months:
            if month not in mapping_covariances:
                raise ValueError(f"mapping covariance missing for {month:%Y-%m}")
            raw.append(mapping_covariances[month])
    else:
        array = np.asarray(mapping_covariances, dtype=float)
        if array.shape == (2, 2):
            raw = [array] * STATE_MONTHS
        elif array.shape == (STATE_MONTHS, 2, 2):
            raw = list(array)
        else:
            raise ValueError("mapping covariances must be 2x2, 4x2x2, or month keyed")
    result = np.zeros((STATE_DIMENSION, STATE_DIMENSION))
    for position, covariance in enumerate(raw):
        block = _month_slice(position)
        result[block, block] = _validated_covariance(
            covariance, 2, name="mapping covariance"
        )
    return result


def joint_quadrant_path_probabilities(
    state: JointGaussianState,
    mapping_covariances: object,
    *,
    sobol_samples: int = 65_536,
    seed: int = 0,
) -> dict[tuple[str, str, str, str], float]:
    """Approximate all 256 four-month quadrant paths deterministically.

    Mapping errors are independent across months at readout, so their 2x2
    covariance matrices are added block-diagonally.  A scrambled Sobol sequence
    with a fixed seed makes the quasi-Monte Carlo approximation reproducible.
    ``sobol_samples`` must be a power of two.
    """

    if (
        not isinstance(sobol_samples, int)
        or sobol_samples < 256
        or sobol_samples & (sobol_samples - 1)
    ):
        raise ValueError("sobol_samples must be a power of two and at least 256")
    total_covariance = state.covariance + _mapping_block_covariance(
        state, mapping_covariances
    )
    total_covariance = _validated_covariance(
        total_covariance,
        STATE_DIMENSION,
        name="path readout covariance",
        positive_definite=True,
    )
    eigenvalues, eigenvectors = np.linalg.eigh(total_covariance)
    root = eigenvectors @ np.diag(np.sqrt(np.maximum(eigenvalues, 0.0)))
    sampler = qmc.Sobol(d=STATE_DIMENSION, scramble=True, seed=int(seed))
    uniforms = sampler.random_base2(int(math.log2(sobol_samples)))
    # Scrambling normally keeps points away from {0, 1}; clipping also protects
    # the normal inverse CDF from an implementation-specific endpoint.
    uniforms = np.clip(
        uniforms,
        np.finfo(float).eps,
        1.0 - np.finfo(float).eps,
    )
    draws = state.mean + norm.ppf(uniforms) @ root.T
    codes = np.empty((sobol_samples, STATE_MONTHS), dtype=np.int8)
    for position in range(STATE_MONTHS):
        growth = draws[:, 2 * position]
        inflation = draws[:, 2 * position + 1]
        codes[:, position] = (
            (growth < 0.0).astype(np.int8)
            + 2 * (inflation < 0.0).astype(np.int8)
        )
        # The binary encoding is the same order as REGIME_ORDER: 0=up/up,
        # 1=down/up, 2=up/down, and 3=down/down.
    codes_wide = codes.astype(np.int64)
    encoded = (
        codes_wide[:, 0] * 64
        + codes_wide[:, 1] * 16
        + codes_wide[:, 2] * 4
        + codes_wide[:, 3]
    )
    counts = np.bincount(encoded, minlength=4**STATE_MONTHS)
    probabilities: dict[tuple[str, str, str, str], float] = {}
    for encoded_path, count in enumerate(counts):
        value = encoded_path
        digits = [0] * STATE_MONTHS
        for position in range(STATE_MONTHS - 1, -1, -1):
            digits[position] = value % 4
            value //= 4
        path = tuple(REGIME_ORDER[digit] for digit in digits)
        probabilities[path] = float(count / sobol_samples)
    return probabilities
